<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Alten.Connected_Vehicles.Infrastructure</RootNamespace>
    <AssemblyName>Alten.Connected_Vehicles.Infrastructure</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.0.0" />
  </ItemGroup>
</Project>
