<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Alten.Connected_vehicle.Model.Test</RootNamespace>
    <AssemblyName>Alten.Connected_vehicle.Model.Test</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alten.Connected_vehicle.Model\Alten.Connected_vehicle.Model.csproj" />
    <ProjectReference Include="..\Alten.Connected_Vehicles.Test.Common\Alten.Connected_Vehicles.Test.Common.csproj" />
  </ItemGroup>
</Project>
