<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Alten.Connected_Vehicles.DTO</RootNamespace>
    <AssemblyName>Alten.Connected_Vehicles.DTO</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alten.Connected_vehicle.Model\Alten.Connected_vehicle.Model.csproj" />
  </ItemGroup>
</Project>
