<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Alten.Connected_Vehicles.MSSQLRepository</RootNamespace>
    <AssemblyName>Alten.Connected_Vehicles.MSSQLRepository</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alten.Connected_Vehicles.Infrastructure\Alten.Connected_Vehicles.Infrastructure.csproj" />
  </ItemGroup>
</Project>
