//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alten.Connected_Vehicles.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawTransction
    {
        public int ID { get; set; }
        public byte[] RawData { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
