//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alten.Connected_Vehicles.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid ID { get; set; }
        public string RegNo { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool Status { get; set; }
    }
}
