//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alten.Connected_Vehicles.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string ID { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
